version: "3.9"

services:
  web:
    image: nginx:latest
    volumes:
     - ./grype-service:/etc/nginx/templates/grype
     - ./trivy-service:/etc/nginx/templates/trivy
     - ./conf.d:/etc/nginx/conf.d/
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
